//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace ianlee { namespace fezhatnode {

ref class fezhatnodeConsumer;

public ref class fezhatnodeSetRedLedStateResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static fezhatnodeSetRedLedStateResult^ CreateSuccessResult()
    {
        auto result = ref new fezhatnodeSetRedLedStateResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static fezhatnodeSetRedLedStateResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new fezhatnodeSetRedLedStateResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class fezhatnodeGetRedLedStateResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool State
    {
        bool get() { return m_interfaceMemberState; }
    internal:
        void set(_In_ bool value) { m_interfaceMemberState = value; }
    }
    
    static fezhatnodeGetRedLedStateResult^ CreateSuccessResult(_In_ bool interfaceMemberState)
    {
        auto result = ref new fezhatnodeGetRedLedStateResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->State = interfaceMemberState;
        return result;
    }
    
    static fezhatnodeGetRedLedStateResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new fezhatnodeGetRedLedStateResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    bool m_interfaceMemberState;
};

public ref class fezhatnodeSetRgbLedD2ColorResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static fezhatnodeSetRgbLedD2ColorResult^ CreateSuccessResult()
    {
        auto result = ref new fezhatnodeSetRgbLedD2ColorResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static fezhatnodeSetRgbLedD2ColorResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new fezhatnodeSetRgbLedD2ColorResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class fezhatnodeSetRgbLedD3ColorResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static fezhatnodeSetRgbLedD3ColorResult^ CreateSuccessResult()
    {
        auto result = ref new fezhatnodeSetRgbLedD3ColorResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static fezhatnodeSetRgbLedD3ColorResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new fezhatnodeSetRgbLedD3ColorResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class fezhatnodeGetLightSensorValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double Value
    {
        double get() { return m_interfaceMemberValue; }
    internal:
        void set(_In_ double value) { m_interfaceMemberValue = value; }
    }
    
    static fezhatnodeGetLightSensorValueResult^ CreateSuccessResult(_In_ double interfaceMemberValue)
    {
        auto result = ref new fezhatnodeGetLightSensorValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Value = interfaceMemberValue;
        return result;
    }
    
    static fezhatnodeGetLightSensorValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new fezhatnodeGetLightSensorValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    double m_interfaceMemberValue;
};

public ref class fezhatnodeGetTemperatureSensorValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double ValueC
    {
        double get() { return m_interfaceMemberValueC; }
    internal:
        void set(_In_ double value) { m_interfaceMemberValueC = value; }
    }
    property double ValueF
    {
        double get() { return m_interfaceMemberValueF; }
    internal:
        void set(_In_ double value) { m_interfaceMemberValueF = value; }
    }
    
    static fezhatnodeGetTemperatureSensorValueResult^ CreateSuccessResult(_In_ double interfaceMemberValueC, _In_ double interfaceMemberValueF)
    {
        auto result = ref new fezhatnodeGetTemperatureSensorValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->ValueC = interfaceMemberValueC;
        result->ValueF = interfaceMemberValueF;
        return result;
    }
    
    static fezhatnodeGetTemperatureSensorValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new fezhatnodeGetTemperatureSensorValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    double m_interfaceMemberValueC;
    double m_interfaceMemberValueF;
};

public ref class fezhatnodeJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property fezhatnodeConsumer^ Consumer
    {
        fezhatnodeConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ fezhatnodeConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    fezhatnodeConsumer^ m_consumer;
};

} } } 
