//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace ianlee { namespace fezhatnode {

ref class fezhatnodeSignals;

public interface class IfezhatnodeSignals
{
    event Windows::Foundation::TypedEventHandler<fezhatnodeSignals^, fezhatnodeButtonDio18PressedReceivedEventArgs^>^ ButtonDio18PressedReceived;
    event Windows::Foundation::TypedEventHandler<fezhatnodeSignals^, fezhatnodeButtonDio22PressedReceivedEventArgs^>^ ButtonDio22PressedReceived;
};

public ref class fezhatnodeSignals sealed : [Windows::Foundation::Metadata::Default] IfezhatnodeSignals
{
public:
    // Calling this method will send the ButtonDio18Pressed signal to every member of the session.
    void ButtonDio18Pressed();

    // This event fires whenever the ButtonDio18Pressed signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<fezhatnodeSignals^, fezhatnodeButtonDio18PressedReceivedEventArgs^>^ ButtonDio18PressedReceived;

    // Calling this method will send the ButtonDio22Pressed signal to every member of the session.
    void ButtonDio22Pressed();

    // This event fires whenever the ButtonDio22Pressed signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<fezhatnodeSignals^, fezhatnodeButtonDio22PressedReceivedEventArgs^>^ ButtonDio22PressedReceived;

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallButtonDio18PressedReceived(_In_ fezhatnodeSignals^ sender, _In_ fezhatnodeButtonDio18PressedReceivedEventArgs^ args);
    void CallButtonDio22PressedReceived(_In_ fezhatnodeSignals^ sender, _In_ fezhatnodeButtonDio22PressedReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    alljoyn_interfacedescription_member m_memberButtonDio18Pressed;
    alljoyn_interfacedescription_member m_memberButtonDio22Pressed;
};

} } } 
